export enum MailTemplateEnum {
    PASSWORD_CREATE = './userRegister',
    FORGOT_PASSOWRD = './forgotPassword',
    RESET_PASSWORD = './resetPassword',
    ORG_CREATE = './organizationCreate',
    PENDING_USER_CREATE = './pendingUserRegister',
    USER_ACTIVATION = './userActivation',
    INF_CREATE = './infCreate',
    INF_ASSIGN = './infAssign',
    INF_APPROVE = './infApprove',
    INF_REJECT = './infReject',
    ORG_DEACTIVATE = './deactivateOrg',
    ORG_REACTIVATE = './reactivateOrg',
    PDD_IC_REJECT = './pddRejectIC',
    PDD_CREATE = './pddCreate',
    MONITORING_CREATE = './monitoringCreate',
    MONITORING_APPROVE = './monitoringApprove',
    MONITORING_REJECT = './monitoringReject',
    VERIFICATION_CREATE_PD = './verificationCreatePD',
    VERIFICATION_CREATE_DNA = './verificationCreateDNA',
    VERIFICATION_APPROVE_IC = './verificationApproveIC',
    VERIFICATION_APPROVE_PD = './verificationApprovePD',
    VERIFICATION_REJECT_IC = './verificationRejectIC',
    VERIFICATION_REJECT_PD = './verificationRejectPD',
}
