export enum MailTemplateEnum {
    PASSWORD_CREATE = './userRegister',
    FORGOT_PASSOWRD = './forgotPassword',
    RESET_PASSWORD = './resetPassword',
    ORG_CREATE = './organizationCreate',
    PENDING_USER_CREATE = './pendingUserRegister',
    USER_ACTIVATION = './userActivation',
    INF_CREATE = './infCreate',
    INF_ASSIGN = './infAssign',
    INF_APPROVE = './infApprove',
    INF_REJECT = './infReject',
    ORG_DEACTIVATE = './deactivateOrg',
    ORG_REACTIVATE = './reactivateOrg',
    PDD_IC_REJECT = './pddRejectIC',
    PDD_CREATE = './pddCreate',
    PDD_APPROVAL_IC_TO_PD = 'pddApprovalICtoPD',
    PDD_APPROVAL_IC_TO_DNA = 'pddApprovalICtoDNA',
    PDD_DNA_REJECT_TO_PD = './pddRejectDNAtoPD',
    PDD_DNA_REJECT_TO_IC = './pddRejectDNAtoIC',
    VR_CREATE = './vrCreate',
    VR_CREATE_DNA = './vrCreateToDNA',
}
