version: "3.3"
volumes:
  data:
    driver: local
  filestore:
    driver: local
services:
  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env.db
    environment:
      # POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /data/postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:Z
      - data:/data/postgres
  national:
    build:
      context: .
      dockerfile: ./backend/services/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env.db
      - .env.national
    environment:
      RUN_MODULE: national-api
      LOCATION_SERVICE: FILE
      ASYNC_OPERATIONS_TYPE: Database
      DOMAIN_MAP: "true"
    volumes:
      - filestore:/app/backend/services/public
      - ./scripts/seed-data/users.csv:/app/backend/services/users.csv:Z
      - ./scripts/seed-data/organisations.csv:/app/backend/services/organisations.csv:Z
  stats:
    build:
      context: .
      dockerfile: ./backend/services/Dockerfile
    ports:
      - "3100:3100"
    depends_on:
      - db
      - national
    env_file:
      - .env.db
      - .env.national
    environment:
      RUN_PORT: 3100
      RUN_MODULE: analytics-api
      DOMAIN_MAP: "true"
  replicator:
    build:
      context: .
      dockerfile: ./backend/services/Dockerfile
    depends_on:
      - db
      - national
    env_file:
      - .env.db
      - .env.replicator
    environment:
      # ,data-importer
      RUN_MODULE: replicator,async-operations-handler
      LOCATION_SERVICE: OPENSTREET
      ASYNC_OPERATIONS_TYPE: Database
    volumes:
      - filestore:/app/backend/services/public
  # async-operations-handler:
  #   build:
  #     context: .
  #     dockerfile: ./backend/services/Dockerfile
  #   depends_on:
  #     - db
  #     - national
  #   environment:
  #     DB_HOST: db
  #     DB_USER: root
  #     DB_PASSWORD: "<ANY PASSOWORD>"
  #     RUN_MODULE: async-operations-handler
  #     SMTP_ENDPOINT: email-smtp.us-east-1.amazonaws.com
  #     SMTP_PASSWORD: "<ANY PASSOWORD>"
  #     ASYNC_OPERATIONS_TYPE: Database
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
      args:
        PORT: ${WEB_PORT}
        REACT_APP_BACKEND: ${REACT_APP_BACKEND}
        REACT_APP_STAT_URL: ${REACT_APP_STAT_URL}
        REACT_APP_COUNTRY_NAME: ${REACT_APP_COUNTRY_NAME}
        REACT_APP_GOVERNMENT_MINISTRY: ${REACT_APP_GOVERNMENT_MINISTRY}
        REACT_APP_COUNTRY_FLAG_URL: ${REACT_APP_COUNTRY_FLAG_URL}
        REACT_APP_COUNTRY_CODE: ${REACT_APP_COUNTRY_CODE}
        REACT_APP_MAP_TYPE: ${REACT_APP_MAP_TYPE}
        REACT_APP_MAPBOXGL_ACCESS_TOKEN: ${REACT_APP_MAPBOXGL_ACCESS_TOKEN}
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    depends_on:
      - db
      - national
