export enum TransactionType {
    TOKEN_CREATION = 'TOKEN_CREATION',
    TOKEN_ASSOCIATION = 'TOKEN_ASSOCIATION',
    TOKEN_MINT = 'TOKEN_MINT',
    TOKEN_TRANSFER = 'TOKEN_TRANSFER',
    TOKEN_BURN = 'TOKEN_BURN',
}
