export enum UserStageEnum {
    VALIDATIONS_N_DATABASE_SAVE = 'VALIDATIONS_N_DATABASE_SAVE',
    GUARDIAN_REGISTER_USER = 'GUARDIAN_REGISTER_USER',
    USER_HEDERA_ACC_GEN = 'USER_HEDERA_ACC_GEN',
    GUARDIAN_CONFIG_UPDATE = 'GUARDIAN_CONFIG_UPDATE',
    GUARDIAN_ASSIGN_POLICY = 'GUARDIAN_ASSIGN_POLICY',
    GUARDIAN_CREATE_GROUP_TYPE = 'GUARDIAN_CREATE_GROUP_TYPE',
    ORGANIZATION_HEDERA_ACC_GEN = 'ORGANIZATION_HEDERA_ACC_GEN',
    GUARDIAN_ORGANIZATION_SAVE = 'GUARDIAN_ORGANIZATION_SAVE',
    GUARDIAN_USER_CREATE = 'GUARDIAN_USER_CREATE',
    GUARDIAN_APPROVE_ORGANIZATION = 'GUARDIAN_APPROVE_ORGANIZATION',
    EMAIL_SENDING = 'EMAIL_SENDING',
    COMPLETED = 'COMPLETED',
}
