export enum UserStageEnum {
    REGISTER = 'REGISTER',
    ASSIGN_REGISTRY = 'ASSIGN_REGISTRY',
    ASSIGN_POLICY = 'ASSIGN_POLICY',
    CREATE_GROUP_TYPE = 'CREATE_GROUP_TYPE',
    CREATE_GROUP = 'CREATE_GROUP',
    CREATE_USER = 'CREATE_USER',
    APPROVE_USER = 'APPROVE_USER',
    COMPLETED = 'COMPLETED',
}
