export enum UserStageEnum {
    REGISTER = 'REGISTER',
    ASIGN_REGISTRY = 'ASIGN_REGISTRY',
    ASIGN_POLICY = 'ASIGN_REGISTRY',
    CREATE_GROUP_TYPE = 'CREATE_GROUP_TYPE',
    CREATE_GROUP = 'CREATE_GROUP',
    CREATE_USER = 'CREATE_USER',
    APPROVE_USER = 'APPROVE_USER',
}
