export enum ProjectSectorEnum {
    ENERGY = 'ENERGY',
    AGRICULTURE = 'AGRICULTURE',
    HEALTH = 'HEALTH',
    EDUCATION = 'EDUCATION',
    TRANSPORT = 'TRANSPORT',
    MANUFACTURING = 'MANUFACTURING',
    HOSPITALITY = 'HOSPITALITY',
    FORESTRY = 'FORESTRY',
    WASTE = 'WASTE',
    OTHER = 'OTHER',
}
