export const SECTOR_TO_SCOPES_MAP: { [key: string]: string[] } = {
  ENERGY: ["ENERGY_INDUSTRIES", "ENERGY_DISTRIBUTION", "ENERGY_DEMAND"],
  AGRICULTURE: ["AGRICULTURE"],
  FORESTRY: ["AFFORESTATION_AND_REFORESTATION"],
  MANUFACTURING: [
    "MANUFACTURING_INDUSTRIES",
    "CHEMICAL_INDUSTRIES",
    "METAL_PRODUCTION",
  ],
  TRANSPORT: ["TRANSPORT"],
  WASTE: ["WASTE_HANDLING_AND_DISPOSAL", "WASTE_FROM_FUELS"],
  OTHER: [
    "CONSTRUCTION",
    "MINING_MINERAL_PRODUCTION",
    "FUGITIVE_EMISSIONS_PRODUCTION",
    "SOLVENT_USE",
  ],
  EDUCATION: ["N/A"],
  HEALTH: ["N/A"],
  HOSPITALITY: ["N/A"],
};
