export const COLOR_CONFIGS = {
  PRIMARY_THEME_COLOR: '#00babe',
  PRIMARY_FONT_COLOR: '#8C8C8C',
  PRIMARY_RED_COLOR: '#FF4D4F',
  SUCCESS_RESPONSE_COLOR: '#70B554',
  FAILED_RESPONSE_COLOR: '#FF4D4F',
  PROCESSED_RESPONSE_COLOR: '#00babe',
};
