export enum TransactionStage {
    USER_REGISTER = 'USER_REGISTER',
    ASSIGN_REGISTRY = 'ASSIGN_REGISTRY',
    ASSIGN_POLICY = 'ASSIGN_POLICY',
    CREATE_GROUP_TYPE = 'CREATE_GROUP_TYPE',
    CREATE_ORGANIZATION_BLOCK = 'CREATE_ORGANIZATION_BLOCK',
    CREATE_USER_BLOCK = 'CREATE_USER_BLOCK',
    CREATE_INVITATION = 'CREATE_INVITATION',
    APPROVE_ORGANIZATION = 'APPROVE_ORGANIZATION',
    REJECT_ORGANIZATION = 'REJECT_ORGANIZATION',
    CHANGE_PASSOWRD = 'CHANGE_PASSOWRD',
}
