export const GUARDIAN_API = {
    LOGIN: '/api/v1/accounts/login',
    REGISTER: '/api/v1/accounts/register',
    ACCESS_TOKEN: '/api/v1/accounts/access-token',
    GENERATE_HEDERA_ACCOUNT: '/api/v1/demo/push/random-key',
    FETCH_TASK_BY_ID: '/api/v1/tasks/',
    PROFILE_UPDATE: '/api/v1/profiles/push',
    CHANGE_PASSWORD: '/api/v1/accounts/change-password',
    POLICY_ASSIGN_ONE: '/api/v1/permissions/users',
    POLICY_ASSIGN_TWO: '/policies/assign',
    POLICIES: '/api/v1/policies/',
    BLOCKS: {
        CREATE_GROUP_TYPE: 'create_organizations',
        CREATE_SINGLE_ORGANIZATION: 'single_organizations_creation_form',
        CREATE_MULTIPLE_ORGANIZATION: 'multiple_organizations_creation_form',
        CREATE_USER: 'user_creation_form',
        USER_CREATE_INVITE: 'user_create_invite',
        APPROVE_ORGANIZATION: 'organizations_active_reject_buttons',
        CREATE_PROJECT: 'project_creation_form',
        CREATE_TOKEN: 'create_token',
        ASSOCIATE_TOKEN: 'associate_token',
        CREATE_ACTIVITY: 'activity_creation_form',
        CREATE_MONITORING_REPORT: 'monitoring_report_creation_form',
        CREATE_VERIFICATION_REPORT: 'verification_report_creation_form',
        CREATE_INF: 'inf_creation_form',
        CREATE_PDD: 'pdd_creation_form',
        CREATE_VALIDATION: 'validation_report_creation_form',
        PROJECT_QUERY: {
            GRID: 'project_grid',
            FILTER_PROJECT_ID: '',
            FILTER_ACTIVITY_ID: '',
            FILTER_REF_ID: 'project_refId_filter',
            FILTER_STATUS: 'project_status_filter',
            FILTER_NOT_STATUS: '',
        },
        USER_QUERY: {
            GRID: 'user_grid',
            FILTER_PROJECT_ID: '',
            FILTER_ACTIVITY_ID: '',
            FILTER_REF_ID: 'user_refId_filter',
            FILTER_STATUS: 'user_status_filter',
            FILTER_NOT_STATUS: 'user_not_status_filter',
        },
        ORGANIZATION_QUERY: {
            GRID: 'organizations_grid',
            FILTER_PROJECT_ID: '',
            FILTER_ACTIVITY_ID: '',
            FILTER_REF_ID: 'organizations_refId_filter',
            FILTER_STATUS: 'organizations_status_filter',
            FILTER_NOT_STATUS: 'organizations_not_status_filter',
        },
        INF_QUERY: {
            GRID: 'inf_grid',
            FILTER_REF_ID: 'inf_refId_filter',
            FILTER_PROJECT_ID: 'inf_project_id_filter',
            FILTER_ACTIVITY_ID: '',
            FILTER_STATUS: 'inf_status_filter',
            FILTER_NOT_STATUS: 'inf_not_status_filter',
        },
        PDD_QUERY: {
            GRID: 'pdd_grid',
            FILTER_REF_ID: 'pdd_refId_filter',
            FILTER_PROJECT_ID: 'pdd_project_id_filter',
            FILTER_ACTIVITY_ID: '',
            FILTER_STATUS: 'pdd_status_filter',
            FILTER_NOT_STATUS: '',
        },
        VALIDATION_QUERY: {
            GRID: 'validation_report_grid',
            FILTER_REF_ID: 'validation_report_refId_filter',
            FILTER_PROJECT_ID: 'validation_report_project_id_filter',
            FILTER_ACTIVITY_ID: '',
            FILTER_STATUS: 'validation_report_status_filter',
            FILTER_NOT_STATUS: 'validation_not_status_filter',
        },
        ACTIVITY_QUERY: {
            GRID: 'activity_grid',
            FILTER_REF_ID: 'activity_refId_filter',
            FILTER_PROJECT_ID: 'activity_project_id_filter',
            FILTER_ACTIVITY_ID: '',
            FILTER_STATUS: 'activity_status_filter',
            FILTER_NOT_STATUS: '',
        },
        MONITORING_QUERY: {
            GRID: 'monitoring_report_grid',
            FILTER_REF_ID: 'monitoring_report_refId_filter',
            FILTER_PROJECT_ID: 'monitoring_report_project_id_filter',
            FILTER_ACTIVITY_ID: 'monitoring_report_activity_id_filter',
            FILTER_STATUS: 'monitoring_report_status_filter',
            FILTER_NOT_STATUS: '',
        },
        VERIFICATION_QUERY: {
            GRID: 'verification_report_grid',
            FILTER_REF_ID: 'verification_report_refId_filter',
            FILTER_PROJECT_ID: 'verification_report_project_id_filter',
            FILTER_ACTIVITY_ID: 'verification_report_activity_id_filter',
            FILTER_STATUS: '',
            FILTER_NOT_STATUS: '',
        },
        APPROVE_REJECT_INF: 'inf_approve_reject_buttons',
        APPROVE_REJECT_PROJECT: 'project_approve_reject_button',
        APPROVE_MONITORING: 'monitoring_report_ic_approve_reject_buttons',
    },
};
